import React from 'react';
import { useTranslation } from 'react-i18next';
import Pagination from '../common/Pagination.jsx';
import DataState from '../common/DataState.jsx';

export default function QueryDataTable({ titleKey, personKey, rows, page, pageMeta, loading, error, severity, type, severityOptions, typeOptions, onSeverityChange, onTypeChange, onRetry, onPageChange, onDetail, displayLine, displayType, displayDescription, displayPerson, getSeverityLabel, getSeverityClass }) {
  const { t } = useTranslation();
  return <div className="table-container"><div className="table-head"><h4>{t(titleKey)}</h4><div className="table-filters"><select className="mini-select" value={severity} onChange={(event) => onSeverityChange(event.target.value)}><option value="">{t('query.filterAllSeverity')}</option>{severityOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select><select className="mini-select" value={type} onChange={(event) => onTypeChange(event.target.value)}><option value="">{t('query.filterAllType')}</option>{typeOptions.map((option) => <option key={option} value={option}>{displayType(option)}</option>)}</select></div></div><div className="table-wrapper"><table className="data-table"><thead><tr><th>{t('query.colDefectId')}</th><th>{t('query.colLineName')}</th><th>{t('query.colLocation')}</th><th>{t('query.colType')}</th><th>{t('query.colDate')}</th><th>{t('query.colSeverity')}</th><th>{t('query.colDesc')}</th><th>{t(personKey)}</th><th>{t('query.colDetail')}</th></tr></thead><tbody><DataState loading={loading} error={error} isEmpty={!rows.length} colSpan={9} onRetry={onRetry} />{rows.map((item) => <tr key={item.id}><td>{item.id}</td><td><span className="cell-clamp cell-line">{displayLine(item.line)}</span></td><td><span className="cell-clamp cell-short">{item.location}</span></td><td><span className="cell-clamp cell-short">{displayType(item.type)}</span></td><td><span className="cell-clamp cell-short">{item.date}</span></td><td><span className={`badge ${getSeverityClass(item.severity)}`}>{getSeverityLabel(item.severity)}</span></td><td><span className="cell-clamp cell-desc">{displayDescription(item.desc)}</span></td><td><span className="cell-clamp cell-short">{displayPerson(item.inspector || item.recorder)}</span></td><td><button className="btn-detail" onClick={() => onDetail(item.id)} type="button">{t('query.viewDetail')}</button></td></tr>)}</tbody></table><Pagination page={page} totalPages={pageMeta.totalPages} totalElements={pageMeta.totalElements} onPageChange={onPageChange} /></div></div>;
}
